#!/bin/bash

RUNNER=$1
ESCUALO_HOST=$2

if [ "master" == $TRAVIS_BRANCH ] && ["false" == $TRAVIS_PULL_REQUEST ]; then
 echo -e "Host $ESCUALO_HOST\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
 chmod 600 deploy_rsa
 mv deploy_rsa ~/.ssh/id_rsa
 git remote add live ssh://root@$ESCUALO_HOST/var/repo/$RUNNER.git
 git push live master

fi
